// <auto-generated />
using System;
using ControleTI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControleTI.Migrations
{
    [DbContext(typeof(ControleTIContext))]
    [Migration("20210215175127_Usuarios2")]
    partial class Usuarios2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ControleTI.Models.Dispositivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MacAdress");

                    b.Property<string>("Nome");

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Dispositivo");
                });

            modelBuilder.Entity("ControleTI.Models.Filial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Filial");
                });

            modelBuilder.Entity("ControleTI.Models.Setor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Setor");
                });

            modelBuilder.Entity("ControleTI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FilialId");

                    b.Property<string>("NomeCompleto");

                    b.Property<string>("NomeUsu");

                    b.Property<int?>("SetorId");

                    b.HasKey("Id");

                    b.HasIndex("FilialId");

                    b.HasIndex("SetorId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ControleTI.Models.Dispositivo", b =>
                {
                    b.HasOne("ControleTI.Models.Usuario")
                        .WithMany("Dispositivo")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("ControleTI.Models.Usuario", b =>
                {
                    b.HasOne("ControleTI.Models.Filial", "Filial")
                        .WithMany()
                        .HasForeignKey("FilialId");

                    b.HasOne("ControleTI.Models.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId");
                });
#pragma warning restore 612, 618
        }
    }
}
